replicaCount: 1

# --- ServiceAccount --------------------------
serviceAccount:
  # Do **not** create a ServiceAccount from the chart; Terraform already
  # created `restaurant-app-ksa` and Helm merely needs to reference it.
  create: true
  name: restaurant-app-ksa
# ---------------------------------------------

# image values are set by Terraform
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

