replicaCount: 1

serviceAccountName: restaurant-app-ksa

# image values are set by Terraform
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

# We're not using Ingress for this project
ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
