{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "restaurant-app.serviceAccountName" . }}
  labels:
    {{- include "restaurant-app.labels" . | nindent 4 }}
  annotations:
    # We will need to create a new GSA for this app and update the name here.
    iam.gke.io/gcp-service-account: restaurant-app-gsa@{{ .Values.projectId }}.iam.gserviceaccount.com
{{- end }}
